### ISSUE TITLE
Component doesn't render on Vue 3 app due to missing ref owner context

### ISSUE THREAD

**Issue by leooliveira-dev** [microsoft/powerbi-client-vue-js#8]
I am currently trying to use this component in a Vue 3.2 app I maintain. However, it fails to render under any circumstance, giving out a console warning as follows:
![image](https://github.com/microsoft/powerbi-client-vue-js/assets/59964798/ae1eedb1-728f-4a2e-8f93-4affaea0ffa6)

Trying to mount the component with the bootstrap config object (empty or undefined as the documentation recommends), the behaviour persists:
![image](https://github.com/microsoft/powerbi-client-vue-js/assets/59964798/7e28ca37-b933-48ac-8134-c7c228c29a18)

Reading online about the error, it might have something to do with [passing the ref to the render function as a string, which should not be done as of Vue 3.](https://stackoverflow.com/questions/62839300/vue-3-refs-is-undefined-in-render-function)

**Comment by leooliveira-dev** [comment]
Ended up re-implementing the library's fundaments into a Vue 3 component inside my project according to my needs and it worked just fine. Will leave the issue open, but might open a PR with my implementation in the future.

**Comment by Mitunkumarsahu** [comment]
i am also facing the same issue.

**Comment by KotanaSai21** [comment]
npm Hello,

We were not able to reproduce the app. Our Demo app is based on vue 3.2, and it was working fine. 

We even tried to create a new vue project `npm create vue@latest` and we were able to embed the report in the vue application.

Could you please provide details that can help us to reproduce this issue?

**Comment by jamesjoung** [comment]
For those having this issue. I had vue 3 component library which we bundled `vue` dependancy with the library using Vite. And using this library on a nuxt vue app started showing this error. After excluding the `vue` dependancy in the bundle and allowing nuxt vue dep to flow through to the library instead, this error is now disappeared..

This issue took me a couple of days to figure out..

**Comment by Mitunkumarsahu** [comment]
Actually vue component for embedding the report library is not working,
even the demo file in official Microsoft documentation is also not working.
That's why I have used another way of embedding the report. You can go
through the code for understanding or else leave a comment so that I can
give the brief explanation.

**Comment by mjmcphail** [comment]
This demo does not work.... the same as many many of the power bi examples provided.  This is a HUGE waste of time.

**Comment by Mitunkumarsahu** [comment]
You must replace the powerbi link and client I'd according to your
application. Make sure you have correctly created azure entra I'd/ active
directory and published the powerbi report.

**Comment by mjmcphail** [comment]
did all those things... this code does not work without changes... see the changes in my repo link.

**Comment by KotanaSai21** [comment]
Thanks for reaching out.  We were able to reproduce this and currently working on this issue. 

@mjmcphail , Thanks for the fix. But, we already identified the issue is with the old versions and upgraded the version in the `package.json` which resolves the issue and have an PR internally with changes ready.

After upgrading all packages to latest version, we identified that [types](https://www.npmjs.com/package/powerbi-client-vue-js?activeTab=code) folder is not getting generated in the dist folder while building the package. Although we were able to embed the report but getting this warning in demo folder while importing package.
![image](https://github.com/microsoft/powerbi-client-vue-js/assets/47911842/8c14ce92-6456-42f3-a4cb-f7773410b93c)

We investigated the issue and found that when we upgraded the `vue-tsc` package to latest 2.0.6 version, we were not able to generate the types folder.  We're currently looking into this issue.  If you have any inputs, please do let us know.

Meanwhile, we will try to release a new beta version of the package this week. We'll keep the `vue-tsc` to old version in this release  and try to resolve this issue as a follow-up item.

**Comment by braiinzz** [comment]
> Thanks for reaching out. We were able to reproduce this and currently working on this issue.
> 
> @mjmcphail , Thanks for the fix. But, we already identified the issue is with the old versions and upgraded the version in the `package.json` which resolves the issue and have an PR internally with changes ready.
> 
> After upgrading all packages to latest version, we identified that [types](https://www.npmjs.com/package/powerbi-client-vue-js?activeTab=code) folder is not getting generated in the dist folder while building the package. Although we were able to embed the report but getting this warning in demo folder while importing package. ![image](https://private-user-images.githubusercontent.com/47911842/311496579-8c14ce92-6456-42f3-a4cb-f7773410b93c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDUyNjAsIm5iZiI6MTcxMTQ0NDk2MCwicGF0aCI6Ii80NzkxMTg0Mi8zMTE0OTY1NzktOGMxNGNlOTItNjQ1Ni00MmYzLWE0Y2ItZjc3NzM0MTBiOTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA5MjI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NDk3ZTFiZTNlMGZmYWJmY2YwZTFlMzE5ZDVhOWM5ODMxY2U1M2JlMDJhOTc3OTNmYmVlYmE0ZDU3N2I1ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8agOP5_woCFlX2-eCTSa0gCPbc7cGTJPruiskoofLSM)
> 
> We investigated the issue and found that when we upgraded the `vue-tsc` package to latest 2.0.6 version, we were not able to generate the types folder. We're currently looking into this issue. If you have any inputs, please do let us know.
> 
> Meanwhile, we will try to release a new beta version of the package this week. We'll keep the `vue-tsc` to old version in this release and try to resolve this issue as a follow-up item.

@KotanaSai21 I wanted to test this vue component this week and got the error as well. Do you already have a beta version of this package ready?

**Comment by KotanaSai21** [comment]
@braiinzz, there are some issues with the Release pipeline to publish the package to npm library. Confirmed now that the issue is fixed with the pipeline. 

Please expect a new version release by tomorrow. Thank you.

**Comment by KotanaSai21** [comment]
We released a new version `1.1.0`. Please install the latest version and let us know if you face any other issues.

**Comment by mjmcphail** [comment]
Why isn't the source on this repo updated?  Hidden shadow repos.  Open source yea right.

**Comment by v-MadhavC** [comment]
Source code is updated.

**Comment by mathieulebasic** [comment]
I still experience the same error with the latest version of this package... Exactly the same message as the one posted before. Any reason for this ?

**Comment by jamesjoung** [comment]
this issue seems to occuring when you have multiple vue instance. My case, Library 1 was packages with vue, Library 2 was also packaged with vue, on our appliication, we installed these two pacakges, some what, these two packages couldnt be used i nthe same context. So what we did was, both library is not packging the vue instead to supply by the application so that same vue references flow through to these two packages fixed it
